version: 2.1

orbs:
  node: circleci/node@5.2

jobs:
   build:
    executor: node/default
    steps:
      - checkout

workflows:
  tests:
    jobs:
      - build:
          filters:
            branches:
              only:
               - development
