version: 2.1

orbs:
  node: circleci/node@5.2

jobs:
   build_deploy_dev:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running build for deploy purpose (development)"
      - run: npm install --prefix ./server
      - run: npm run test --prefix ./server
      - run: npm run build --prefix ./server
      - run: npm install --prefix ./client
      - run: npm run test --prefix ./client
      - run: npm run build:dev:linux --prefix ./client
      - run: npm install
      - run: node deploy_server.js
      - run: node deploy_client.js
      - run: ssh-keyscan -H 's21.mydevil.net' >> ~/.ssh/known_hosts
   
   build_deploy_prod:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running build for deploy purpose (production)"
      - run: npm install --prefix ./server
      - run: npm run test --prefix ./server
      - run: npm run build --prefix ./server
      - run: npm install --prefix ./client
      - run: npm run test --prefix ./client
      - run: npm run build:prod:linux --prefix ./client
      - run: npm install
      - run: node deploy_server_prod.js
      - run: node deploy_client_prod.js
      - run: ssh-keyscan -H 's21.mydevil.net' >> ~/.ssh/known_hosts

workflows:
  tm-workflow:
    jobs:
      - build_deploy_dev:
          filters:
            branches:
              only:
              - development
      - build_deploy_prod:
          filters:
            branches:
              only:
              - master
