version: 2.1

orbs:
  node: circleci/node@5.2

jobs:
  build_server_dev:
    - run: npm install --prefix ./server
    - run: npm run test --prefix ./server
    - run: npm run build --prefix ./server
    - save_cache:
        key: dependency-cache-server-{{ checksum "server/package.json" }}
        paths:
          - ./server/node_modules
          - ./server/dist

  build_client_dev:
    - run: npm install --prefix ./client
    - run: npm run test --prefix ./client
    - run: npm run build:dev:linux --prefix ./client
    - save_cache:
        key: dependency-cache-client-{{ checksum "client/package.json" }}
        paths:
          - ./client/node_modules
          - ./client/build

  build_deploy_dev:
    - run: npm install

  deploy_server_dev:
    - restore_cache:
        key: dependency-cache-server-{{ checksum "server/package.json" }}
    - run: node deploy_server.js

  deploy_client_dev:
    - restore_cache:
        key: dependency-cache-client-{{ checksum "client/package.json" }}
    - run: node deploy_client.js

workflows:
  tm-workflow:
    jobs:
      - build_server_dev:
          filters:
            branches:
              only:
              - development

      - build_client_dev:
          requires:
            - build_server_dev:
              - success
          filters:
            branches:
              only:
              - development

      - build_deploy_dev:
          requires:
            - build_server_dev:
              - success
            - build_client_dev:
              - success
          filters:
            branches:
              only:
              - development

      - deploy_server_dev:
          requires:
            - build_deploy_dev:
              - success
            - build_server_dev:
              - success
          filters:
            branches:
              only:
              - development

      - deploy_client_dev:
          requires:
            - build_deploy_dev:
              - success
            - build_client_dev:
              - success
          filters:
            branches:
              only:
              - development
              
      - domain_restart_dev:
          requires:
            - deploy_server_dev:
              - success
            - deploy_client_dev:
              - success
          filters:
            branches:
              only:
              - development
