version: 2.1

orbs:
  node: circleci/node@5.2

jobs:
   build_deploy:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running build for deploy purpose"
      - run: npm install
   build_server:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running build for server application"
      - run: npm install --prefix ./server
      - run: npm run test --prefix ./server
      - run: npm run build --prefix ./server
   build_client:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running build for client application"
      - run: npm install --prefix ./client
      - run: npm run test --prefix ./client
      - run: npm run build:dev:linux --prefix ./client
   deploy_development:
    executor: node/default
    steps:
      - checkout
      - run: node deploy_server.js
      - run: node deploy_client.js
      - run: ssh-keyscan -H 's21.mydevil.net' >> ~/.ssh/known_hosts
   deploy_production:
    executor: node/default
    steps:
      - checkout

workflows:
  tm-workflow:
    jobs:
      - build_server:
          filters:
            branches:
              only:
              - development
              - master
      - build_client:
          requires:
            - build_server
          filters:
            branches:
              only:
                - development
                - master
      - build_deploy:
          requires:
            - build_client
          filters:
            branches:
              only:
                - development
                - naster
      - deploy_development:
          requires:
            - build_deploy
          filters:
            branches:
              only:
                - development
      - deploy_production:
          filters:
            branches:
              only:
                - master
