version: 2.1

orbs:
  node: circleci/node@5.2

jobs:
   build_server:
    executor: node/default
    steps:
      - checkout
      - run: echo "Running build for server application"
      - run: cd server
      - run: npm install

workflows:
  tests:
    jobs:
      - build_server:
          filters:
            branches:
              only:
               - development
